bytes allocated, allocations, type, function, file:line
           2560	             10	core.thread.Thread D main src/profilegc.d:77
            640	             10	int[] profilegc.main.bar src/profilegc.d:73
            288	              1	immutable(char)[][int] D main src/profilegc.d:34
            240	              4	core.thread.Thread[] D main src/profilegc.d:77
            160	              1	float[][] D main src/profilegc.d:18
            160	              1	int[][] D main src/profilegc.d:15
             64	              1	float[] D main src/profilegc.d:53
             64	              1	int[] D main src/profilegc.d:52
             32	              1	profilegc.main.C D main src/profilegc.d:12
             16	              1	char[] D main src/profilegc.d:45
             16	              1	char[] D main src/profilegc.d:47
             16	              1	closure profilegc.main.foo src/profilegc.d:57
             16	              1	float D main src/profilegc.d:16
             16	              1	float[] D main src/profilegc.d:17
             16	              1	int D main src/profilegc.d:13
             16	              1	int[] D main src/profilegc.d:14
             16	              1	int[] D main src/profilegc.d:33
             16	              1	int[] D main src/profilegc.d:48
             16	              1	wchar[] D main src/profilegc.d:46
